// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: DESARROLLO_DE_HMI

#ifndef _DESARROLLO_DE_HMI_UI_H
#define _DESARROLLO_DE_HMI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_HOME.h"
#include "ui_MONITOREO_.h"
#include "ui_CONFIGURACIONES.h"
#include "ui_WIFI.h"
#include "ui_ALERTAS.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_561359873);    // assets/casa (1).png
LV_IMG_DECLARE(ui_img_configuraciones_png);    // assets/configuraciones.png
LV_IMG_DECLARE(ui_img_534919753);    // assets/wifi (2).png
LV_IMG_DECLARE(ui_img_spyware_png);    // assets/spyware.png
LV_IMG_DECLARE(ui_img_peligro_png);    // assets/peligro.png
LV_IMG_DECLARE(ui_img_eliminar_png);    // assets/eliminar.png
LV_IMG_DECLARE(ui_img_361177371);    // assets/gota-de-agua.png
LV_IMG_DECLARE(ui_img_1354942385);    // assets/caminante (1).png
LV_IMG_DECLARE(ui_img_destello_png);    // assets/destello.png
LV_IMG_DECLARE(ui_img_551389857);    // assets/temperatura-alta (2).png
LV_IMG_DECLARE(ui_img_1515518950);    // assets/wifi (1).png
LV_IMG_DECLARE(ui_img_compartir_png);    // assets/compartir.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
