// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: DESARROLLO_DE_HMI

#ifndef UI_ALERTAS_H
#define UI_ALERTAS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ALERTAS
extern void ui_ALERTAS_screen_init(void);
extern void ui_ALERTAS_screen_destroy(void);
extern lv_obj_t * ui_ALERTAS;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_ALERT;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Panel24;
extern lv_obj_t * ui_Panel25;
extern lv_obj_t * ui_Image30;
extern lv_obj_t * ui_Image31;
extern lv_obj_t * ui_Image32;
extern lv_obj_t * ui_Image33;
extern lv_obj_t * ui_Image34;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Panel26;
extern lv_obj_t * ui_Panel27;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Image35;
extern lv_obj_t * ui_Image36;
extern lv_obj_t * ui_Image37;
extern lv_obj_t * ui_Image38;
extern lv_obj_t * ui_Image39;
extern lv_obj_t * ui_Image40;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Panel28;
extern lv_obj_t * ui_Panel29;
extern lv_obj_t * ui_Panel30;
extern lv_obj_t * ui_Panel31;
extern lv_obj_t * ui_Panel32;
extern lv_obj_t * ui_Panel33;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

