// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: DESARROLLO_DE_HMI

#include "ui.h"

lv_obj_t * ui_ALERTAS = NULL;
lv_obj_t * ui_Panel21 = NULL;
lv_obj_t * ui_ALERT = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_Panel22 = NULL;
lv_obj_t * ui_Panel23 = NULL;
lv_obj_t * ui_Panel24 = NULL;
lv_obj_t * ui_Panel25 = NULL;
lv_obj_t * ui_Image30 = NULL;
lv_obj_t * ui_Image31 = NULL;
lv_obj_t * ui_Image32 = NULL;
lv_obj_t * ui_Image33 = NULL;
lv_obj_t * ui_Image34 = NULL;
lv_obj_t * ui_Label36 = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_Label38 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_Panel26 = NULL;
lv_obj_t * ui_Panel27 = NULL;
lv_obj_t * ui_Label40 = NULL;
lv_obj_t * ui_Label41 = NULL;
lv_obj_t * ui_Image35 = NULL;
lv_obj_t * ui_Image36 = NULL;
lv_obj_t * ui_Image37 = NULL;
lv_obj_t * ui_Image38 = NULL;
lv_obj_t * ui_Image39 = NULL;
lv_obj_t * ui_Image40 = NULL;
lv_obj_t * ui_Label42 = NULL;
lv_obj_t * ui_Label43 = NULL;
lv_obj_t * ui_Label44 = NULL;
lv_obj_t * ui_Label45 = NULL;
lv_obj_t * ui_Label46 = NULL;
lv_obj_t * ui_Label47 = NULL;
lv_obj_t * ui_Panel28 = NULL;
lv_obj_t * ui_Panel29 = NULL;
lv_obj_t * ui_Panel30 = NULL;
lv_obj_t * ui_Panel31 = NULL;
lv_obj_t * ui_Panel32 = NULL;
lv_obj_t * ui_Panel33 = NULL;
// event funtions

// build funtions

void ui_ALERTAS_screen_init(void)
{
    ui_ALERTAS = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ALERTAS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel21 = lv_obj_create(ui_ALERTAS);
    lv_obj_set_width(ui_Panel21, 505);
    lv_obj_set_height(ui_Panel21, 51);
    lv_obj_set_x(ui_Panel21, -1);
    lv_obj_set_y(ui_Panel21, -120);
    lv_obj_set_align(ui_Panel21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ALERT = lv_img_create(ui_ALERTAS);
    lv_img_set_src(ui_ALERT, &ui_img_peligro_png);
    lv_obj_set_width(ui_ALERT, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ALERT, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ALERT, 216);
    lv_obj_set_y(ui_ALERT, -115);
    lv_obj_set_align(ui_ALERT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ALERT, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ALERT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label35 = lv_label_create(ui_ALERTAS);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, 24);
    lv_obj_set_y(ui_Label35, -116);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "ALERTAS");

    ui_Panel22 = lv_obj_create(ui_ALERTAS);
    lv_obj_set_width(ui_Panel22, 206);
    lv_obj_set_height(ui_Panel22, 62);
    lv_obj_set_x(ui_Panel22, -117);
    lv_obj_set_y(ui_Panel22, -51);
    lv_obj_set_align(ui_Panel22, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel23 = lv_obj_create(ui_ALERTAS);
    lv_obj_set_width(ui_Panel23, 206);
    lv_obj_set_height(ui_Panel23, 62);
    lv_obj_set_x(ui_Panel23, -117);
    lv_obj_set_y(ui_Panel23, 17);
    lv_obj_set_align(ui_Panel23, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel24 = lv_obj_create(ui_ALERTAS);
    lv_obj_set_width(ui_Panel24, 206);
    lv_obj_set_height(ui_Panel24, 62);
    lv_obj_set_x(ui_Panel24, 117);
    lv_obj_set_y(ui_Panel24, -51);
    lv_obj_set_align(ui_Panel24, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel25 = lv_obj_create(ui_ALERTAS);
    lv_obj_set_width(ui_Panel25, 206);
    lv_obj_set_height(ui_Panel25, 62);
    lv_obj_set_x(ui_Panel25, 117);
    lv_obj_set_y(ui_Panel25, 17);
    lv_obj_set_align(ui_Panel25, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image30 = lv_img_create(ui_ALERTAS);
    lv_img_set_src(ui_Image30, &ui_img_534919753);
    lv_obj_set_width(ui_Image30, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image30, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image30, -221);
    lv_obj_set_y(ui_Image30, -117);
    lv_obj_set_align(ui_Image30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image30, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image31 = lv_img_create(ui_ALERTAS);
    lv_img_set_src(ui_Image31, &ui_img_configuraciones_png);
    lv_obj_set_width(ui_Image31, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image31, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image31, -178);
    lv_obj_set_y(ui_Image31, -116);
    lv_obj_set_align(ui_Image31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image31, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image32 = lv_img_create(ui_ALERTAS);
    lv_img_set_src(ui_Image32, &ui_img_561359873);
    lv_obj_set_width(ui_Image32, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image32, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image32, -133);
    lv_obj_set_y(ui_Image32, -115);
    lv_obj_set_align(ui_Image32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image32, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image33 = lv_img_create(ui_ALERTAS);
    lv_img_set_src(ui_Image33, &ui_img_spyware_png);
    lv_obj_set_width(ui_Image33, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image33, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image33, -88);
    lv_obj_set_y(ui_Image33, -116);
    lv_obj_set_align(ui_Image33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image33, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image34 = lv_img_create(ui_ALERTAS);
    lv_img_set_src(ui_Image34, &ui_img_peligro_png);
    lv_obj_set_width(ui_Image34, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image34, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image34, -44);
    lv_obj_set_y(ui_Image34, -116);
    lv_obj_set_align(ui_Image34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image34, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label36 = lv_label_create(ui_ALERTAS);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, -114);
    lv_obj_set_y(ui_Label36, -64);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "TEMPERATURA");

    ui_Label37 = lv_label_create(ui_ALERTAS);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 121);
    lv_obj_set_y(ui_Label37, -64);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "HUMEDAD");

    ui_Label38 = lv_label_create(ui_ALERTAS);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, -117);
    lv_obj_set_y(ui_Label38, 6);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "POTENCIA");

    ui_Label39 = lv_label_create(ui_ALERTAS);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, 114);
    lv_obj_set_y(ui_Label39, 6);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "WIFI");

    ui_Panel26 = lv_obj_create(ui_ALERTAS);
    lv_obj_set_width(ui_Panel26, 206);
    lv_obj_set_height(ui_Panel26, 62);
    lv_obj_set_x(ui_Panel26, -117);
    lv_obj_set_y(ui_Panel26, 86);
    lv_obj_set_align(ui_Panel26, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel27 = lv_obj_create(ui_ALERTAS);
    lv_obj_set_width(ui_Panel27, 206);
    lv_obj_set_height(ui_Panel27, 62);
    lv_obj_set_x(ui_Panel27, 117);
    lv_obj_set_y(ui_Panel27, 86);
    lv_obj_set_align(ui_Panel27, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label40 = lv_label_create(ui_ALERTAS);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, -116);
    lv_obj_set_y(ui_Label40, 73);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "MOVIMIENTO");

    ui_Label41 = lv_label_create(ui_ALERTAS);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 120);
    lv_obj_set_y(ui_Label41, 73);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "FIREBASE");

    ui_Image35 = lv_img_create(ui_ALERTAS);
    lv_img_set_src(ui_Image35, &ui_img_551389857);
    lv_obj_set_width(ui_Image35, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image35, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image35, -190);
    lv_obj_set_y(ui_Image35, -43);
    lv_obj_set_align(ui_Image35, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image35, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image36 = lv_img_create(ui_ALERTAS);
    lv_img_set_src(ui_Image36, &ui_img_destello_png);
    lv_obj_set_width(ui_Image36, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image36, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image36, -190);
    lv_obj_set_y(ui_Image36, 25);
    lv_obj_set_align(ui_Image36, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image36, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image37 = lv_img_create(ui_ALERTAS);
    lv_img_set_src(ui_Image37, &ui_img_1354942385);
    lv_obj_set_width(ui_Image37, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image37, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image37, -190);
    lv_obj_set_y(ui_Image37, 93);
    lv_obj_set_align(ui_Image37, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image37, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image38 = lv_img_create(ui_ALERTAS);
    lv_img_set_src(ui_Image38, &ui_img_361177371);
    lv_obj_set_width(ui_Image38, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image38, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image38, 45);
    lv_obj_set_y(ui_Image38, -44);
    lv_obj_set_align(ui_Image38, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image38, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image39 = lv_img_create(ui_ALERTAS);
    lv_img_set_src(ui_Image39, &ui_img_compartir_png);
    lv_obj_set_width(ui_Image39, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image39, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image39, 45);
    lv_obj_set_y(ui_Image39, 92);
    lv_obj_set_align(ui_Image39, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image39, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image40 = lv_img_create(ui_ALERTAS);
    lv_img_set_src(ui_Image40, &ui_img_534919753);
    lv_obj_set_width(ui_Image40, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image40, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image40, 45);
    lv_obj_set_y(ui_Image40, 23);
    lv_obj_set_align(ui_Image40, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image40, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label42 = lv_label_create(ui_ALERTAS);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, -116);
    lv_obj_set_y(ui_Label42, -36);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "ACTIVO");

    ui_Label43 = lv_label_create(ui_ALERTAS);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, -116);
    lv_obj_set_y(ui_Label43, 32);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "ACTIVO");

    ui_Label44 = lv_label_create(ui_ALERTAS);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, -116);
    lv_obj_set_y(ui_Label44, 100);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "ACTIVO");

    ui_Label45 = lv_label_create(ui_ALERTAS);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, 117);
    lv_obj_set_y(ui_Label45, -36);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "FALLA");

    ui_Label46 = lv_label_create(ui_ALERTAS);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, 117);
    lv_obj_set_y(ui_Label46, 32);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "FALLA");

    ui_Label47 = lv_label_create(ui_ALERTAS);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, 117);
    lv_obj_set_y(ui_Label47, 100);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "ACTIVO");

    ui_Panel28 = lv_obj_create(ui_ALERTAS);
    lv_obj_set_width(ui_Panel28, 10);
    lv_obj_set_height(ui_Panel28, 10);
    lv_obj_set_x(ui_Panel28, -37);
    lv_obj_set_y(ui_Panel28, -64);
    lv_obj_set_align(ui_Panel28, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel29 = lv_obj_create(ui_ALERTAS);
    lv_obj_set_width(ui_Panel29, 10);
    lv_obj_set_height(ui_Panel29, 10);
    lv_obj_set_x(ui_Panel29, -37);
    lv_obj_set_y(ui_Panel29, 6);
    lv_obj_set_align(ui_Panel29, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel30 = lv_obj_create(ui_ALERTAS);
    lv_obj_set_width(ui_Panel30, 10);
    lv_obj_set_height(ui_Panel30, 10);
    lv_obj_set_x(ui_Panel30, -37);
    lv_obj_set_y(ui_Panel30, 73);
    lv_obj_set_align(ui_Panel30, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel31 = lv_obj_create(ui_ALERTAS);
    lv_obj_set_width(ui_Panel31, 10);
    lv_obj_set_height(ui_Panel31, 10);
    lv_obj_set_x(ui_Panel31, 194);
    lv_obj_set_y(ui_Panel31, -64);
    lv_obj_set_align(ui_Panel31, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel32 = lv_obj_create(ui_ALERTAS);
    lv_obj_set_width(ui_Panel32, 10);
    lv_obj_set_height(ui_Panel32, 10);
    lv_obj_set_x(ui_Panel32, 194);
    lv_obj_set_y(ui_Panel32, 6);
    lv_obj_set_align(ui_Panel32, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel33 = lv_obj_create(ui_ALERTAS);
    lv_obj_set_width(ui_Panel33, 10);
    lv_obj_set_height(ui_Panel33, 10);
    lv_obj_set_x(ui_Panel33, 194);
    lv_obj_set_y(ui_Panel33, 73);
    lv_obj_set_align(ui_Panel33, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_ALERTAS_screen_destroy(void)
{
    if(ui_ALERTAS) lv_obj_del(ui_ALERTAS);

    // NULL screen variables
    ui_ALERTAS = NULL;
    ui_Panel21 = NULL;
    ui_ALERT = NULL;
    ui_Label35 = NULL;
    ui_Panel22 = NULL;
    ui_Panel23 = NULL;
    ui_Panel24 = NULL;
    ui_Panel25 = NULL;
    ui_Image30 = NULL;
    ui_Image31 = NULL;
    ui_Image32 = NULL;
    ui_Image33 = NULL;
    ui_Image34 = NULL;
    ui_Label36 = NULL;
    ui_Label37 = NULL;
    ui_Label38 = NULL;
    ui_Label39 = NULL;
    ui_Panel26 = NULL;
    ui_Panel27 = NULL;
    ui_Label40 = NULL;
    ui_Label41 = NULL;
    ui_Image35 = NULL;
    ui_Image36 = NULL;
    ui_Image37 = NULL;
    ui_Image38 = NULL;
    ui_Image39 = NULL;
    ui_Image40 = NULL;
    ui_Label42 = NULL;
    ui_Label43 = NULL;
    ui_Label44 = NULL;
    ui_Label45 = NULL;
    ui_Label46 = NULL;
    ui_Label47 = NULL;
    ui_Panel28 = NULL;
    ui_Panel29 = NULL;
    ui_Panel30 = NULL;
    ui_Panel31 = NULL;
    ui_Panel32 = NULL;
    ui_Panel33 = NULL;

}
