// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: DESARROLLO_DE_HMI

#ifndef UI_CONFIGURACIONES_H
#define UI_CONFIGURACIONES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CONFIGURACIONES
extern void ui_CONFIGURACIONES_screen_init(void);
extern void ui_CONFIGURACIONES_screen_destroy(void);
extern lv_obj_t * ui_CONFIGURACIONES;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image28;
extern lv_obj_t * ui_Panel34;
extern lv_obj_t * ui_Switch5;
extern lv_obj_t * ui_Switch6;
extern lv_obj_t * ui_Switch7;
extern lv_obj_t * ui_Switch8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

