// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: DESARROLLO_DE_HMI

#include "ui.h"

lv_obj_t * ui_CONFIGURACIONES = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Switch3 = NULL;
lv_obj_t * ui_Switch4 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Image22 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Image28 = NULL;
lv_obj_t * ui_Panel34 = NULL;
lv_obj_t * ui_Switch5 = NULL;
lv_obj_t * ui_Switch6 = NULL;
lv_obj_t * ui_Switch7 = NULL;
lv_obj_t * ui_Switch8 = NULL;
// event funtions

// build funtions

void ui_CONFIGURACIONES_screen_init(void)
{
    ui_CONFIGURACIONES = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CONFIGURACIONES, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel7 = lv_obj_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Panel7, 388);
    lv_obj_set_height(ui_Panel7, 50);
    lv_obj_set_x(ui_Panel7, -40);
    lv_obj_set_y(ui_Panel7, -60);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel11 = lv_obj_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Panel11, 505);
    lv_obj_set_height(ui_Panel11, 51);
    lv_obj_set_x(ui_Panel11, 0);
    lv_obj_set_y(ui_Panel11, -120);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel9 = lv_obj_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Panel9, 388);
    lv_obj_set_height(ui_Panel9, 50);
    lv_obj_set_x(ui_Panel9, -40);
    lv_obj_set_y(ui_Panel9, 47);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel8 = lv_obj_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Panel8, 388);
    lv_obj_set_height(ui_Panel8, 50);
    lv_obj_set_x(ui_Panel8, -40);
    lv_obj_set_y(ui_Panel8, -7);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel10 = lv_obj_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Panel10, 388);
    lv_obj_set_height(ui_Panel10, 50);
    lv_obj_set_x(ui_Panel10, -40);
    lv_obj_set_y(ui_Panel10, 101);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -65);
    lv_obj_set_y(ui_Label19, -57);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "GUARDAR DATOS DE HUMEDAD");

    ui_Label22 = lv_label_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -54);
    lv_obj_set_y(ui_Label22, -5);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "GUARDAR DATOS DE TEMPERATURA");

    ui_Label23 = lv_label_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -69);
    lv_obj_set_y(ui_Label23, 47);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "GUARDAR DATOS DE POTENCIA");

    ui_Label24 = lv_label_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -59);
    lv_obj_set_y(ui_Label24, 100);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "GUARDAR DATOS DE MOVIMIENTO");

    ui_Switch1 = lv_switch_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 117);
    lv_obj_set_y(ui_Switch1, -60);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Switch2 = lv_switch_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 117);
    lv_obj_set_y(ui_Switch2, -7);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    ui_Switch3 = lv_switch_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, 117);
    lv_obj_set_y(ui_Switch3, 47);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);

    ui_Switch4 = lv_switch_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Switch4, 50);
    lv_obj_set_height(ui_Switch4, 25);
    lv_obj_set_x(ui_Switch4, 117);
    lv_obj_set_y(ui_Switch4, 101);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);

    ui_Label25 = lv_label_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 24);
    lv_obj_set_y(ui_Label25, -117);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "CONFIGURACIONES");

    ui_Image7 = lv_img_create(ui_CONFIGURACIONES);
    lv_img_set_src(ui_Image7, &ui_img_361177371);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, -208);
    lv_obj_set_y(ui_Image7, -60);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_CONFIGURACIONES);
    lv_img_set_src(ui_Image8, &ui_img_1354942385);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, -208);
    lv_obj_set_y(ui_Image8, 100);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_CONFIGURACIONES);
    lv_img_set_src(ui_Image9, &ui_img_destello_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image9, -208);
    lv_obj_set_y(ui_Image9, 47);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_img_create(ui_CONFIGURACIONES);
    lv_img_set_src(ui_Image14, &ui_img_551389857);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image14, -211);
    lv_obj_set_y(ui_Image14, -6);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image22 = lv_img_create(ui_CONFIGURACIONES);
    lv_img_set_src(ui_Image22, &ui_img_configuraciones_png);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image22, 214);
    lv_obj_set_y(ui_Image22, -115);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_CONFIGURACIONES);
    lv_img_set_src(ui_Image10, &ui_img_534919753);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image10, -220);
    lv_obj_set_y(ui_Image10, -115);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_CONFIGURACIONES);
    lv_img_set_src(ui_Image11, &ui_img_561359873);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image11, -176);
    lv_obj_set_y(ui_Image11, -115);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_img_create(ui_CONFIGURACIONES);
    lv_img_set_src(ui_Image12, &ui_img_spyware_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image12, -128);
    lv_obj_set_y(ui_Image12, -116);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image28 = lv_img_create(ui_CONFIGURACIONES);
    lv_img_set_src(ui_Image28, &ui_img_peligro_png);
    lv_obj_set_width(ui_Image28, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image28, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image28, -82);
    lv_obj_set_y(ui_Image28, -116);
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel34 = lv_obj_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Panel34, 65);
    lv_obj_set_height(ui_Panel34, 212);
    lv_obj_set_x(ui_Panel34, 201);
    lv_obj_set_y(ui_Panel34, 21);
    lv_obj_set_align(ui_Panel34, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch5 = lv_switch_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Switch5, 50);
    lv_obj_set_height(ui_Switch5, 25);
    lv_obj_set_x(ui_Switch5, 201);
    lv_obj_set_y(ui_Switch5, -60);
    lv_obj_set_align(ui_Switch5, LV_ALIGN_CENTER);

    ui_Switch6 = lv_switch_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Switch6, 50);
    lv_obj_set_height(ui_Switch6, 25);
    lv_obj_set_x(ui_Switch6, 201);
    lv_obj_set_y(ui_Switch6, -7);
    lv_obj_set_align(ui_Switch6, LV_ALIGN_CENTER);

    ui_Switch7 = lv_switch_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Switch7, 50);
    lv_obj_set_height(ui_Switch7, 25);
    lv_obj_set_x(ui_Switch7, 201);
    lv_obj_set_y(ui_Switch7, 47);
    lv_obj_set_align(ui_Switch7, LV_ALIGN_CENTER);

    ui_Switch8 = lv_switch_create(ui_CONFIGURACIONES);
    lv_obj_set_width(ui_Switch8, 50);
    lv_obj_set_height(ui_Switch8, 25);
    lv_obj_set_x(ui_Switch8, 201);
    lv_obj_set_y(ui_Switch8, 101);
    lv_obj_set_align(ui_Switch8, LV_ALIGN_CENTER);

}

void ui_CONFIGURACIONES_screen_destroy(void)
{
    if(ui_CONFIGURACIONES) lv_obj_del(ui_CONFIGURACIONES);

    // NULL screen variables
    ui_CONFIGURACIONES = NULL;
    ui_Panel7 = NULL;
    ui_Panel11 = NULL;
    ui_Panel9 = NULL;
    ui_Panel8 = NULL;
    ui_Panel10 = NULL;
    ui_Label19 = NULL;
    ui_Label22 = NULL;
    ui_Label23 = NULL;
    ui_Label24 = NULL;
    ui_Switch1 = NULL;
    ui_Switch2 = NULL;
    ui_Switch3 = NULL;
    ui_Switch4 = NULL;
    ui_Label25 = NULL;
    ui_Image7 = NULL;
    ui_Image8 = NULL;
    ui_Image9 = NULL;
    ui_Image14 = NULL;
    ui_Image22 = NULL;
    ui_Image10 = NULL;
    ui_Image11 = NULL;
    ui_Image12 = NULL;
    ui_Image28 = NULL;
    ui_Panel34 = NULL;
    ui_Switch5 = NULL;
    ui_Switch6 = NULL;
    ui_Switch7 = NULL;
    ui_Switch8 = NULL;

}
