// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: DESARROLLO_DE_HMI

#include "ui.h"

lv_obj_t * ui_HOME = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_Image26 = NULL;
// event funtions
void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CANCEL) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CANCEL) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Dropdown1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        dropdown_navegacion(e);
    }
}

// build funtions

void ui_HOME_screen_init(void)
{
    ui_HOME = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HOME, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME, lv_color_hex(0xF3F4F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Panel1, 140);
    lv_obj_set_height(ui_Panel1, 140);
    lv_obj_set_x(ui_Panel1, -162);
    lv_obj_set_y(ui_Panel1, -20);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Panel5, 140);
    lv_obj_set_height(ui_Panel5, 140);
    lv_obj_set_x(ui_Panel5, -10);
    lv_obj_set_y(ui_Panel5, -20);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -165);
    lv_obj_set_y(ui_Label1, -59);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Temperatura °C");

    ui_Label2 = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -24);
    lv_obj_set_y(ui_Label2, -59);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Humedad");
    lv_obj_set_scrollbar_mode(ui_Label2, LV_SCROLLBAR_MODE_OFF);

    ui_Label3 = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -166);
    lv_obj_set_y(ui_Label3, -17);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "25 °C");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -12);
    lv_obj_set_y(ui_Label4, -17);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "27 %");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_HOME);
    lv_obj_set_width(ui_TextArea1, 42);
    lv_obj_set_height(ui_TextArea1, 29);
    lv_obj_set_x(ui_TextArea1, -169);
    lv_obj_set_y(ui_TextArea1, 26);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1, "22");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");
    lv_obj_set_scrollbar_mode(ui_TextArea1, LV_SCROLLBAR_MODE_OFF);

    ui_Keyboard1 = lv_keyboard_create(ui_HOME);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 300);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, -45);
    lv_obj_set_y(ui_Keyboard1, 34);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Label5 = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -207);
    lv_obj_set_y(ui_Label5, 28);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "SP:");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Panel2, 157);
    lv_obj_set_height(ui_Panel2, 140);
    lv_obj_set_x(ui_Panel2, 150);
    lv_obj_set_y(ui_Panel2, -20);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_HOME);
    lv_obj_set_width(ui_Arc1, 130);
    lv_obj_set_height(ui_Arc1, 133);
    lv_obj_set_x(ui_Arc1, 153);
    lv_obj_set_y(ui_Arc1, -9);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);

    ui_Label6 = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 121);
    lv_obj_set_y(ui_Label6, 0);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "V:");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea2 = lv_textarea_create(ui_HOME);
    lv_obj_set_width(ui_TextArea2, 44);
    lv_obj_set_height(ui_TextArea2, 29);
    lv_obj_set_x(ui_TextArea2, 115);
    lv_obj_set_y(ui_TextArea2, -1);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea2, "00");
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");
    lv_obj_set_scrollbar_mode(ui_TextArea2, LV_SCROLLBAR_MODE_OFF);

    ui_Keyboard2 = lv_keyboard_create(ui_HOME);
    lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard2, 300);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_x(ui_Keyboard2, 55);
    lv_obj_set_y(ui_Keyboard2, 48);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Button1 = lv_btn_create(ui_HOME);
    lv_obj_set_width(ui_Button1, 140);
    lv_obj_set_height(ui_Button1, 45);
    lv_obj_set_x(ui_Button1, -6);
    lv_obj_set_y(ui_Button1, 95);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_HOME);
    lv_obj_set_width(ui_Button2, 140);
    lv_obj_set_height(ui_Button2, 45);
    lv_obj_set_x(ui_Button2, -162);
    lv_obj_set_y(ui_Button2, 95);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -165);
    lv_obj_set_y(ui_Label7, 95);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "STAR");

    ui_Label8 = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -7);
    lv_obj_set_y(ui_Label8, 95);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "STOP");

    ui_Dropdown1 = lv_dropdown_create(ui_HOME);
    lv_dropdown_set_options(ui_Dropdown1, "UATOMATICO \nMANUAL");
    lv_obj_set_width(ui_Dropdown1, 158);
    lv_obj_set_height(ui_Dropdown1, 36);
    lv_obj_set_x(ui_Dropdown1, 152);
    lv_obj_set_y(ui_Dropdown1, 102);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Panel6 = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Panel6, 507);
    lv_obj_set_height(ui_Panel6, 51);
    lv_obj_set_x(ui_Panel6, -1);
    lv_obj_set_y(ui_Panel6, -120);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -2);
    lv_obj_set_y(ui_Label10, -115);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "HOME");

    ui_Label11 = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 143);
    lv_obj_set_y(ui_Label11, 70);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "OPERACION");

    ui_Label12 = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 158);
    lv_obj_set_y(ui_Label12, -115);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "10:30 AM");

    ui_Image6 = lv_img_create(ui_HOME);
    lv_img_set_src(ui_Image6, &ui_img_wifi_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, 99);
    lv_obj_set_y(ui_Image6, -117);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_img_create(ui_HOME);
    lv_img_set_src(ui_Image15, &ui_img_561359873);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image15, 217);
    lv_obj_set_y(ui_Image15, -116);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_img_create(ui_HOME);
    lv_img_set_src(ui_Image16, &ui_img_configuraciones_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image16, -175);
    lv_obj_set_y(ui_Image16, -115);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_img_create(ui_HOME);
    lv_img_set_src(ui_Image17, &ui_img_534919753);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image17, -220);
    lv_obj_set_y(ui_Image17, -115);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image18 = lv_img_create(ui_HOME);
    lv_img_set_src(ui_Image18, &ui_img_spyware_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image18, -126);
    lv_obj_set_y(ui_Image18, -114);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image26 = lv_img_create(ui_HOME);
    lv_img_set_src(ui_Image26, &ui_img_peligro_png);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image26, -80);
    lv_obj_set_y(ui_Image26, -115);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_TextArea2);
    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);

}

void ui_HOME_screen_destroy(void)
{
    if(ui_HOME) lv_obj_del(ui_HOME);

    // NULL screen variables
    ui_HOME = NULL;
    ui_Panel1 = NULL;
    ui_Panel5 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_TextArea1 = NULL;
    ui_Keyboard1 = NULL;
    ui_Label5 = NULL;
    ui_Panel2 = NULL;
    ui_Arc1 = NULL;
    ui_Label6 = NULL;
    ui_TextArea2 = NULL;
    ui_Keyboard2 = NULL;
    ui_Button1 = NULL;
    ui_Button2 = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;
    ui_Dropdown1 = NULL;
    ui_Panel6 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Image6 = NULL;
    ui_Image15 = NULL;
    ui_Image16 = NULL;
    ui_Image17 = NULL;
    ui_Image18 = NULL;
    ui_Image26 = NULL;

}
