// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: DESARROLLO_DE_HMI

#include "ui.h"

lv_obj_t * ui_MONITOREO_ = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Atras = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Chart2 = NULL;
lv_obj_t * ui_Button9 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Image21 = NULL;
lv_obj_t * ui_Image27 = NULL;
lv_obj_t * ui_Panel15 = NULL;
lv_obj_t * ui_Panel16 = NULL;
lv_obj_t * ui_Panel17 = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Panel18 = NULL;
lv_obj_t * ui_Panel19 = NULL;
lv_obj_t * ui_Panel20 = NULL;
lv_obj_t * ui_Image19 = NULL;
lv_obj_t * ui_Image20 = NULL;
lv_obj_t * ui_Image23 = NULL;
lv_obj_t * ui_Image24 = NULL;
// event funtions
void ui_event_Atras(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HOME, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_HOME_screen_init);
    }
}

// build funtions

void ui_MONITOREO__screen_init(void)
{
    ui_MONITOREO_ = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MONITOREO_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Panel4, 505);
    lv_obj_set_height(ui_Panel4, 51);
    lv_obj_set_x(ui_Panel4, -1);
    lv_obj_set_y(ui_Panel4, -120);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Atras = lv_btn_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Atras, 156);
    lv_obj_set_height(ui_Atras, 32);
    lv_obj_set_x(ui_Atras, 114);
    lv_obj_set_y(ui_Atras, -117);
    lv_obj_set_align(ui_Atras, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Atras, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Atras, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -20);
    lv_obj_set_y(ui_Label9, -116);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "MONITOREO");

    ui_Panel3 = lv_obj_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Panel3, 356);
    lv_obj_set_height(ui_Panel3, 173);
    lv_obj_set_x(ui_Panel3, 50);
    lv_obj_set_y(ui_Panel3, 5);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chart2 = lv_chart_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Chart2, 289);
    lv_obj_set_height(ui_Chart2, 131);
    lv_obj_set_x(ui_Chart2, 65);
    lv_obj_set_y(ui_Chart2, -6);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart2, 24);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 0, 50);
    lv_chart_set_div_line_count(ui_Chart2, 6, 5);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 12);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 0, 2, false, 25);
    lv_chart_series_t * ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0xFF0000),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 0, 10, 20, 40, 50, 50, 50, 50, 50, 50, 50, 50, 30, 20, 10, 5 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);
    lv_chart_series_t * ui_Chart2_series_2 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x0715F5),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart2_series_2_array[] = { 0, 10, 20, 40, 8, 80, 40, 20, 70, 80 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_2, ui_Chart2_series_2_array);
    lv_chart_series_t * ui_Chart2_series_3 = lv_chart_add_series(ui_Chart2, lv_color_hex(0xFB7900),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart2_series_3_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_3, ui_Chart2_series_3_array);

    ui_Button9 = lv_btn_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Button9, 40);
    lv_obj_set_height(ui_Button9, 20);
    lv_obj_set_x(ui_Button9, -155);
    lv_obj_set_y(ui_Button9, -41);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Button3, 40);
    lv_obj_set_height(ui_Button3, 20);
    lv_obj_set_x(ui_Button3, -210);
    lv_obj_set_y(ui_Button3, -41);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_btn_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Button4, 40);
    lv_obj_set_height(ui_Button4, 20);
    lv_obj_set_x(ui_Button4, -156);
    lv_obj_set_y(ui_Button4, -8);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button5 = lv_btn_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Button5, 40);
    lv_obj_set_height(ui_Button5, 20);
    lv_obj_set_x(ui_Button5, -210);
    lv_obj_set_y(ui_Button5, -9);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button6 = lv_btn_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Button6, 40);
    lv_obj_set_height(ui_Button6, 20);
    lv_obj_set_x(ui_Button6, -210);
    lv_obj_set_y(ui_Button6, 23);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button7 = lv_btn_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Button7, 40);
    lv_obj_set_height(ui_Button7, 20);
    lv_obj_set_x(ui_Button7, -156);
    lv_obj_set_y(ui_Button7, 23);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -210);
    lv_obj_set_y(ui_Label13, -41);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Lun");

    ui_Label14 = lv_label_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -155);
    lv_obj_set_y(ui_Label14, -41);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Mar");

    ui_Label15 = lv_label_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -209);
    lv_obj_set_y(ui_Label15, -8);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Mie");

    ui_Label16 = lv_label_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -155);
    lv_obj_set_y(ui_Label16, -8);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Jue");

    ui_Label17 = lv_label_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -211);
    lv_obj_set_y(ui_Label17, 24);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Vie");

    ui_Label18 = lv_label_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -156);
    lv_obj_set_y(ui_Label18, 23);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Sab");

    ui_Button8 = lv_btn_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Button8, 40);
    lv_obj_set_height(ui_Button8, 20);
    lv_obj_set_x(ui_Button8, -210);
    lv_obj_set_y(ui_Button8, 53);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -210);
    lv_obj_set_y(ui_Label20, 52);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Dom");

    ui_Label26 = lv_label_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 132);
    lv_obj_set_y(ui_Label26, -115);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Borrar Datos");

    ui_Image21 = lv_img_create(ui_MONITOREO_);
    lv_img_set_src(ui_Image21, &ui_img_eliminar_png);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image21, 58);
    lv_obj_set_y(ui_Image21, -116);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image27 = lv_img_create(ui_MONITOREO_);
    lv_img_set_src(ui_Image27, &ui_img_spyware_png);
    lv_obj_set_width(ui_Image27, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image27, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image27, 218);
    lv_obj_set_y(ui_Image27, -114);
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel15 = lv_obj_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Panel15, 89);
    lv_obj_set_height(ui_Panel15, 24);
    lv_obj_set_x(ui_Panel15, 182);
    lv_obj_set_y(ui_Panel15, 114);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel16 = lv_obj_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Panel16, 100);
    lv_obj_set_height(ui_Panel16, 24);
    lv_obj_set_x(ui_Panel16, -66);
    lv_obj_set_y(ui_Panel16, 114);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel17 = lv_obj_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Panel17, 113);
    lv_obj_set_height(ui_Panel17, 24);
    lv_obj_set_x(ui_Panel17, 61);
    lv_obj_set_y(ui_Panel17, 114);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label34 = lv_label_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, 183);
    lv_obj_set_y(ui_Label34, 114);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "HUMEDAD");
    lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 63);
    lv_obj_set_y(ui_Label33, 114);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "TEMPERATURA");
    lv_obj_set_style_text_font(ui_Label33, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -68);
    lv_obj_set_y(ui_Label32, 114);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "POTENCIA");
    lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Panel18, 15);
    lv_obj_set_height(ui_Panel18, 15);
    lv_obj_set_x(ui_Panel18, -125);
    lv_obj_set_y(ui_Panel18, 114);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0xFB7900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Panel19, 15);
    lv_obj_set_height(ui_Panel19, 15);
    lv_obj_set_x(ui_Panel19, -4);
    lv_obj_set_y(ui_Panel19, 114);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel20 = lv_obj_create(ui_MONITOREO_);
    lv_obj_set_width(ui_Panel20, 15);
    lv_obj_set_height(ui_Panel20, 15);
    lv_obj_set_x(ui_Panel20, 129);
    lv_obj_set_y(ui_Panel20, 114);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x0715F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image19 = lv_img_create(ui_MONITOREO_);
    lv_img_set_src(ui_Image19, &ui_img_534919753);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image19, -220);
    lv_obj_set_y(ui_Image19, -115);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_img_create(ui_MONITOREO_);
    lv_img_set_src(ui_Image20, &ui_img_configuraciones_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image20, -176);
    lv_obj_set_y(ui_Image20, -115);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image23 = lv_img_create(ui_MONITOREO_);
    lv_img_set_src(ui_Image23, &ui_img_561359873);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image23, -130);
    lv_obj_set_y(ui_Image23, -115);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image24 = lv_img_create(ui_MONITOREO_);
    lv_img_set_src(ui_Image24, &ui_img_peligro_png);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image24, -88);
    lv_obj_set_y(ui_Image24, -116);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Atras, ui_event_Atras, LV_EVENT_ALL, NULL);

}

void ui_MONITOREO__screen_destroy(void)
{
    if(ui_MONITOREO_) lv_obj_del(ui_MONITOREO_);

    // NULL screen variables
    ui_MONITOREO_ = NULL;
    ui_Panel4 = NULL;
    ui_Atras = NULL;
    ui_Label9 = NULL;
    ui_Panel3 = NULL;
    ui_Chart2 = NULL;
    ui_Button9 = NULL;
    ui_Button3 = NULL;
    ui_Button4 = NULL;
    ui_Button5 = NULL;
    ui_Button6 = NULL;
    ui_Button7 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_Label15 = NULL;
    ui_Label16 = NULL;
    ui_Label17 = NULL;
    ui_Label18 = NULL;
    ui_Button8 = NULL;
    ui_Label20 = NULL;
    ui_Label26 = NULL;
    ui_Image21 = NULL;
    ui_Image27 = NULL;
    ui_Panel15 = NULL;
    ui_Panel16 = NULL;
    ui_Panel17 = NULL;
    ui_Label34 = NULL;
    ui_Label33 = NULL;
    ui_Label32 = NULL;
    ui_Panel18 = NULL;
    ui_Panel19 = NULL;
    ui_Panel20 = NULL;
    ui_Image19 = NULL;
    ui_Image20 = NULL;
    ui_Image23 = NULL;
    ui_Image24 = NULL;

}
