// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: DESARROLLO_DE_HMI

#ifndef UI_MONITOREO__H
#define UI_MONITOREO__H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MONITOREO_
extern void ui_MONITOREO__screen_init(void);
extern void ui_MONITOREO__screen_destroy(void);
extern lv_obj_t * ui_MONITOREO_;
extern lv_obj_t * ui_Panel4;
extern void ui_event_Atras(lv_event_t * e);
extern lv_obj_t * ui_Atras;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Image27;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Image24;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

