// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: DESARROLLO_DE_HMI

#include "ui.h"

lv_obj_t * ui_WIFI = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_Panel14 = NULL;
lv_obj_t * ui_Image25 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_Dropdown2 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_TextArea3 = NULL;
lv_obj_t * ui_Button10 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Keyboard3 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Image29 = NULL;
// event funtions
void ui_event_TextArea3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// build funtions

void ui_WIFI_screen_init(void)
{
    ui_WIFI = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WIFI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel12 = lv_obj_create(ui_WIFI);
    lv_obj_set_width(ui_Panel12, 505);
    lv_obj_set_height(ui_Panel12, 51);
    lv_obj_set_x(ui_Panel12, 0);
    lv_obj_set_y(ui_Panel12, -121);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel13 = lv_obj_create(ui_WIFI);
    lv_obj_set_width(ui_Panel13, 229);
    lv_obj_set_height(ui_Panel13, 209);
    lv_obj_set_x(ui_Panel13, -116);
    lv_obj_set_y(ui_Panel13, 18);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel14 = lv_obj_create(ui_WIFI);
    lv_obj_set_width(ui_Panel14, 189);
    lv_obj_set_height(ui_Panel14, 209);
    lv_obj_set_x(ui_Panel14, 121);
    lv_obj_set_y(ui_Panel14, 18);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image25 = lv_img_create(ui_WIFI);
    lv_img_set_src(ui_Image25, &ui_img_1515518950);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image25, -119);
    lv_obj_set_y(ui_Image25, -33);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_WIFI);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -123);
    lv_obj_set_y(ui_Label27, 78);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, " Red Actual:  MiCasa_5G  ");

    ui_Label28 = lv_label_create(ui_WIFI);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -155);
    lv_obj_set_y(ui_Label28, 102);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, " IP: 192.168.1.100");

    ui_Label29 = lv_label_create(ui_WIFI);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -129);
    lv_obj_set_y(ui_Label29, 36);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Estado:   Conectado");

    ui_Dropdown2 = lv_dropdown_create(ui_WIFI);
    lv_dropdown_set_options(ui_Dropdown2, "Seleccionar Red");
    lv_obj_set_width(ui_Dropdown2, 164);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 123);
    lv_obj_set_y(ui_Dropdown2, -7);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label30 = lv_label_create(ui_WIFI);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 121);
    lv_obj_set_y(ui_Label30, -60);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, " Conectarse a una Red");

    ui_TextArea3 = lv_textarea_create(ui_WIFI);
    lv_obj_set_width(ui_TextArea3, 164);
    lv_obj_set_height(ui_TextArea3, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_TextArea3, 123);
    lv_obj_set_y(ui_TextArea3, 48);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea3, "Clave de wifi: ******");
    lv_textarea_set_placeholder_text(ui_TextArea3, "Placeholder...");
    lv_textarea_set_one_line(ui_TextArea3, true);

    ui_Button10 = lv_btn_create(ui_WIFI);
    lv_obj_set_width(ui_Button10, 124);
    lv_obj_set_height(ui_Button10, 26);
    lv_obj_set_x(ui_Button10, 125);
    lv_obj_set_y(ui_Button10, 95);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_WIFI);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 40);
    lv_obj_set_y(ui_Label21, -116);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "CONFIGURACION DE RED");

    ui_Label31 = lv_label_create(ui_WIFI);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 125);
    lv_obj_set_y(ui_Label31, 95);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Conectarse");

    ui_Keyboard3 = lv_keyboard_create(ui_WIFI);
    lv_obj_set_width(ui_Keyboard3, 300);
    lv_obj_set_height(ui_Keyboard3, 120);
    lv_obj_set_x(ui_Keyboard3, 78);
    lv_obj_set_y(ui_Keyboard3, 69);
    lv_obj_set_align(ui_Keyboard3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Image2 = lv_img_create(ui_WIFI);
    lv_img_set_src(ui_Image2, &ui_img_spyware_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image2, -130);
    lv_obj_set_y(ui_Image2, -116);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_WIFI);
    lv_img_set_src(ui_Image4, &ui_img_configuraciones_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image4, -176);
    lv_obj_set_y(ui_Image4, -116);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_WIFI);
    lv_img_set_src(ui_Image5, &ui_img_561359873);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image5, -219);
    lv_obj_set_y(ui_Image5, -116);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_img_create(ui_WIFI);
    lv_img_set_src(ui_Image13, &ui_img_534919753);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image13, 213);
    lv_obj_set_y(ui_Image13, -116);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image29 = lv_img_create(ui_WIFI);
    lv_img_set_src(ui_Image29, &ui_img_peligro_png);
    lv_obj_set_width(ui_Image29, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image29, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image29, -85);
    lv_obj_set_y(ui_Image29, -115);
    lv_obj_set_align(ui_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image29, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard3, ui_TextArea3);

}

void ui_WIFI_screen_destroy(void)
{
    if(ui_WIFI) lv_obj_del(ui_WIFI);

    // NULL screen variables
    ui_WIFI = NULL;
    ui_Panel12 = NULL;
    ui_Panel13 = NULL;
    ui_Panel14 = NULL;
    ui_Image25 = NULL;
    ui_Label27 = NULL;
    ui_Label28 = NULL;
    ui_Label29 = NULL;
    ui_Dropdown2 = NULL;
    ui_Label30 = NULL;
    ui_TextArea3 = NULL;
    ui_Button10 = NULL;
    ui_Label21 = NULL;
    ui_Label31 = NULL;
    ui_Keyboard3 = NULL;
    ui_Image2 = NULL;
    ui_Image4 = NULL;
    ui_Image5 = NULL;
    ui_Image13 = NULL;
    ui_Image29 = NULL;

}
